### PR TITLE
Artemis Tests

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Create ArtemisMQ - fix conenction url pattern, correct journal timed buffer setting as fsync is disabled.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
also reverting to make ArtemisMQ to extend JmsMQ (jms 1.1 sync send) so only changes are to client and broker config, as to try work out what change caused issue. as don't have access to env to diagnose/look what might be wrong.

**Comment by adamw** [comment]
I suppose the revert to JmsMq is not necessary, as I can just use the `ActiveMq` impl in the tests, instead of `ArtemisMq`

**Comment by michaelandrepearce** [comment]
Yes it is, as in the revert to JmsMq because ActiveMq uses the wrong client and you need to use the artemis client really (activemq5 is supported for compatibility reasons, but as said in main your blog, its like taking kafka 0.7 client with 0.11 broker...its not best if you want perf)

Ive actually debugged the issue low and behold it is my code in jms2MQ - there goes my scala skills, i knew they're not so good, if you couldn't tell by the why i typed it more in java style, its causing it to pause on each send massively.

 if you merge the PR which at least gets you onto right client , note I've also turned on transaction also, this will help for the interim whilst i sort out my code in jms2mq, this is what clebert suggested, but i don't think he noted you were using the activemq5 client.

In the mean time i can brush up my scala a bit better rather than writing java code in scala. It be good if you could run and let us know

**Comment by adamw** [comment]
Sure, I'll try with these settings.

The `CountDownLatch` looked good ... the `MqSender.send` method *should* block until all the messages are confirmed as sent - that's how the current test framework works (in a synchronous way). So I can't see anything wrong there :)

**Comment by adamw** [comment]
So with this setup on 1 client node and 1 client thread I'm getting 7.2k sent/second (vs. 4.1k in the previous setup - so a big improvement), and 4.7k received/second (vs. 4.1k in the previous setup - so not a big change).

**Comment by adamw** [comment]
Unfortunately, with 5 threads and 1 node (both sender & receiver), I'm getting worse performance, on average 8k msgs/second vs 14k msgs/second in the old setup. The rates seems to be quite uneven: https://snapshot.raintank.io/dashboard/snapshot/cEIYVRZKZimsAHED3gbgissLJafnuy4m

Note that I changes max-global-size to 1G as per Clebert's suggestion - maybe that has an impact?

**Comment by adamw** [comment]
With max-global-size 8G I'm getting better performance with 5 threads/1node: 14k received, 20k/s sent: https://snapshot.raintank.io/dashboard/snapshot/E0cZUBOV6DWQ63tPuF76Su8YdhfWcSJt

But this again was the suspect of the server dying when there are more clients. So what would be the correct setting here?

**Comment by michaelandrepearce** [comment]
This is suspect. Essentially the consumer should def be able to exceed consuming more msg per sec than you can produce. I haven't looked at the consuming code yet, let me eyeball that. 

I'm currently off ill today so it maybe later today if I feel better if not tomorrow.

What semantics are you expecting on consumer side btw?

**Comment by michaelandrepearce** [comment]
Eg is at least once delivery ok? As like kafka. Does it need to be transactional?

**Comment by adamw** [comment]
At-least-once, like all other queues. No need for transactions. The receiving code needs to receive a batch of messages and then separately acknowledge them (but the ack can be async)

Get better soon :)

**Comment by michaelandrepearce** [comment]
Why do you not acknowledge as the code receives them. This is quite an odd jms pattern.

**Comment by adamw** [comment]
Well to get at-least-once. The code receives messages, "processes" them (in this case does nothing, but still has the possibility), and only when processing is done deletes/acks them.

**Comment by michaelandrepearce** [comment]
So the processing has to be in batch?

**Comment by michaelandrepearce** [comment]
Or it can be one at a time?

**Comment by adamw** [comment]
It doesn't have to, but it can be, as that's potentially faster. All the queues are given the opportunity to receive & ack messages in batches of up to 10.

**Comment by michaelandrepearce** [comment]
Ive just sent pr, to just make consumer ack async (currently its blocking) and to not constrain the consumer buffer.

re max-global-size 8G, 

as per documentation thats actually in broker.xml

>  the system will enter into page mode once you hit this limit.
             This is an estimate in bytes of how much the messages are using in memory
              The system will use half of the available memory (-Xmx) by default for the global-max-size.
              You may specify a different value here if you need to customize it to your needs.
        
So if you have 16G heap i would leave it at 8G. unless there is an issue I'm missing.

**Pull request merged**
